-- 1. Tabla Principal: USUARIO
CREATE TABLE USUARIO (
    ci VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    clave VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL
);

CREATE TABLE ROL (
    ci VARCHAR(20),
    rol VARCHAR(50),
    PRIMARY KEY (ci, rol),
    FOREIGN KEY (ci) REFERENCES USUARIO(ci) ON DELETE CASCADE
);

CREATE TABLE DOCENTE (
    ci VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (ci) REFERENCES USUARIO(ci) ON DELETE CASCADE
);

CREATE TABLE ADMINISTRADOR (
    ci VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (ci) REFERENCES USUARIO(ci) ON DELETE CASCADE
);

CREATE TABLE TECNICO (
    ci VARCHAR(20) PRIMARY KEY,
    FOREIGN KEY (ci) REFERENCES USUARIO(ci) ON DELETE CASCADE
);


