CREATE DATABASE IF NOT EXISTS sgrsi;
USE sgrsi;

CREATE TABLE IF NOT EXISTS USUARIO (
    ci CHAR(8) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    clave VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_usuario PRIMARY KEY (ci)
);

CREATE TABLE IF NOT EXISTS CORREO (
    ci CHAR(8) NOT NULL,
    correo VARCHAR(100) UNIQUE NOT NULL,
    CONSTRAINT pk_correo PRIMARY KEY (ci, correo),
    CONSTRAINT fk_correo_usuario FOREIGN KEY (ci) 
        REFERENCES USUARIO (ci) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS DOCENTE (
    ci CHAR(8) NOT NULL,
    CONSTRAINT pk_docente PRIMARY KEY (ci),
      CONSTRAINT fk_docente_usuario FOREIGN KEY (ci) 
        REFERENCES USUARIO (ci) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS ADMINISTRADOR(
    ci CHAR(8) NOT NULL,
    CONSTRAINT pk_administrador PRIMARY KEY (ci),
    CONSTRAINT fk_administrador_usuario FOREIGN KEY (ci) 
        REFERENCES USUARIO (ci) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TECNICO(
    ci CHAR(8),
    CONSTRAINT  pk_tecnico PRIMARY KEY (ci),
     CONSTRAINT fk_tecnico_usuario FOREIGN KEY (ci) 
        REFERENCES USUARIO (ci) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS administrador_modifica_usuario (
    id INT AUTO_INCREMENT NOT NULL,
    ciAdministrador CHAR(8) NOT NULL,
    ciUsuario CHAR(8) NOT NULL,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    tipoInteraccion VARCHAR(50) NOT NULL,
    CONSTRAINT pk_admin_modifica_usuario PRIMARY KEY (id),
    CONSTRAINT fk_amu_admin FOREIGN KEY (ciAdministrador) 
        REFERENCES ADMINISTRADOR (ci) 
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_amu_usuario FOREIGN KEY (ciUsuario) 
        REFERENCES USUARIO (ci) 
        ON DELETE CASCADE ON UPDATE CASCADE
);