CREATE DATABASE IF NOT EXISTS sgrsi;
USE sgrsi;

CREATE TABLE USUARIO (
    ci VARCHAR(8),
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL,
    clave VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_usuario PRIMARY KEY (ci)
);

CREATE TABLE ROL (
    ci CHAR(8),
    rol VARCHAR(50),
    CONSTRAINT pk_rol
    PRIMARY KEY (ci, rol)
   
);

CREATE TABLE DOCENTE (
    ci CHAR(8),
    CONSTRAINT pk_docente
    PRIMARY KEY (ci)
);

CREATE TABLE ADMINISTRADOR (
    ci CHAR(8) ,
    CONSTRAINT pk_administrador
    PRIMARY KEY (ci) 
);

CREATE TABLE TECNICO (
    ci CHAR(8),
    CONSTRAINT  pk_tecnico
    PRIMARY KEY (ci)
);

ALTER TABLE ROL 
    ADD CONSTRAINT fk_rol_usuario 
    FOREIGN KEY (ci) REFERENCES USUARIO (ci) 
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DOCENTE 
    ADD CONSTRAINT fk_docente_usuario 
    FOREIGN KEY (ci) REFERENCES USUARIO (ci) 
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE ADMINISTRADOR 
    ADD CONSTRAINT fk_administrador_usuario 
    FOREIGN KEY (ci) REFERENCES USUARIO (ci) 
    ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TECNICO 
    ADD CONSTRAINT fk_tecnico_usuario 
    FOREIGN KEY (ci) REFERENCES USUARIO (ci) 
    ON DELETE CASCADE ON UPDATE CASCADE;

