<?php 

/*

TOFEAT : SE IMPLEMENTAN NUEVOS CONTROLADORES PARA PÁGINAS QUE TRABAJAN CON MÁS DE UN CONTROLADOR

ESTE ARCHIVO ES CREADO DEBIDO A QUE "gestionInventarioTecnologico.php
REQUIERE MAS DE UNA DEPENDENCIA O "require_once" PARA FUNCIONAR, HACIENDO QUE,
AL LLAMAR LOS PROCESOS PARA CARGAR EQUIPOS Y CARGAR UBICACIONES, PASE LO SIGUIENTE:

- SE CARGA EL 1ER MODULO
- SE CARGA VISTA (ERROR: FALTA 2DO MODULO)
- SE CARGA EL 2DO MODULO

ESTE FLUJO HACE QUE EL .php CORRESPONDIENTE NO SE LE PROPORCIONEN TODAS LAS VARIABLES
REQUERIDAS PARA TRABAJAR, ESTE ARCHIVO BUSCA IMPLEMENTAR LAS FUENTES FALTANTES ANTES DE
LLAMAR AL ARCHIVO.

ADEMÁS, SE BUSCA NO ASIGNARLE RESPONSABILIDADES DE CONTROLADOR A LA CAPA VISTA, EN ESTE CASO
SE EVITABA QUE EL ARCHIVO ALOJADO EN PUBLIC PREPARE LOS DATOS ANTES DE MOSTRAR LA PÁGINA VISTA
*/

require_once __DIR__ . "/../../../app/controlador/recursos/procesarCargarEquipos.php";
require_once __DIR__ . "/../../../app/controlador/recursos/procesarCargarUbicaciones.php";

require_once __DIR__ . "/../../../app/vista/administracion/gestionInventarioTecnologico.php";
?>